name = "schedule-guiyang8-33"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SCHEDULE_KV"
id = "6a08c97d81c5489aa0f73be62c798627"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = false
fallbacks = []

[assets]
directory = "./public"

[[r2_buckets]]
binding = "COMMUNITY_R2"
bucket_name = "community-media"

[[d1_databases]]
binding = "COMMUNITY_DB"
database_name = "community_db"
database_id = "6d9636b4-a7a9-4451-a701-7f48df456c6e"

[vars]
GDRIVE_FOLDER_ID = "1JLM76eGeMI7AJB3PXiuPAQzEnt9AJhtg"

[build]
command = "node scripts/build-worker.mjs"
