name = "schedule-guiyang8-33-api"
main = "src/index.ts"
compatibility_date = "2026-04-10"

[[d1_databases]]
binding = "COMMUNITY_DB"
database_name = "community_db"
database_id = "6d9636b4-a7a9-4451-a701-7f48df456c6e"

[vars]
APP_NAME = "schedule-guiyang8-33-api"
